version: '3'
services:
  product:
    image: pagonxt/product
    build: product # docker build ./product -t pagonxt/product
  account:
    image: pagonxt/account
    build: account # docker build ./account -t pagonxt/account
    