openapi: 3.0.1
info:
  version: 1.0.0
  title: Product Restful API
  description: Restful API that deals with Products
  contact:
    name: Dev Contacts
    url: 'https://www.alura.com.br'
    email: devs@alura.com.br
servers:
  - url: 'http://localhost:3000'
    description: Server 1
paths:
  /products:
    summary: creates a product
    description: 'Given provided product data, creates a product in the database'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductData'
      responses:
        201:
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedProductData'
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductData'

components:
  schemas:
    ImagemData:
      type: object
      properties:
        url:
          type: string
        descricao:
          type: string
    CaracteristicaData:
      type: object
      properties:
        nome:
          type: string
        descricao:
          type: string
    ProductData:
      type: object
      properties:
        usuarioId:
          type: string
        nome:
          type: string
        descricao:
          type: string
        categoria:
          type: string
        quantidade:
          type: integer
        valor:
          type: number
        caracteristicas:
          type: array
          items:
            $ref: '#/components/schemas/CaracteristicaData'
        imagens:
          type: array
          items:
            $ref: '#/components/schemas/ImagemData'
    CreatedProductData:
      type: object
      properties:
        usuarioId:
          type: string
        createdDate:
          type: string
        id:
          type: string
        nome:
          type: string
        descricao:
          type: string
        categoria:
          type: string
        quantidade:
          type: integer
        valor:
          type: number
        caracteristicas:
          type: array
          items:
            $ref: '#/components/schemas/CaracteristicaData'
        imagens:
          type: array
          items:
            $ref: '#/components/schemas/ImagemData'